import streamlit as st
import pandas as pd
import numpy as np
import math
import plotly.graph_objects as go
import joblib 

# Hard-linked to your ML pipeline
from ml_pipeline import predict_with_explanations

# --- Configuration & UI Setup ---
st.set_page_config(page_title="G.E.M.I.N.I. Donor Kidney Predictor", page_icon="🩺", layout="wide")

st.markdown("""
    <style>
    .stTabs [data-baseweb="tab-list"] { gap: 24px; border-bottom: 2px solid #E5E7EB; }
    .stTabs [data-baseweb="tab"] { height: 50px; white-space: pre-wrap; font-size: 16px; font-weight: 600;}
    .stTabs [aria-selected="true"] { color: #0369a1 !important; border-bottom: 3px solid #0369a1 !important; }
    div[data-testid="stMetricValue"] { font-size: 1.8rem; color: #1F2937; }
    </style>
""", unsafe_allow_html=True)

# --- Legal & Clinical Safeguard ---
st.warning("""
**⚠️ FOR RESEARCH & EDUCATIONAL USE ONLY.** This tool is a predictive model trained on historical OPTN data. It is **not** FDA cleared and is **not** a substitute for surgical judgment. Do not enter any Protected Health Information (PHI) such as UNOS IDs, names, or birthdates.
""")

# --- Load the Deployment Model ---
@st.cache_resource
def load_model():
    try:
        # Actually loads the freeze-dried model generated by ml_pipeline.py
        return joblib.load('kidney_utilization_lgbm.pkl')
    except FileNotFoundError:
        st.error("🛑 Critical Error: Model file 'kidney_utilization_lgbm.pkl' not found. Please execute `python ml_pipeline.py` to train the algorithm before launching the dashboard.")
        st.stop() # Halts the app so it doesn't crash or show fake data

deployed_model = load_model()

# --- OPTN KDRI/KDPI Calculation Engine (Rao et al. 2009) ---
def calculate_kdri(age, height_cm, weight_kg, eth_black, htn, diab, cod_cva, creat, hcv, dcd):
    """Calculates the Kidney Donor Risk Index based on standard OPTN coefficients."""
    xb = 0.0
    
    if age < 18:
        xb += 0.0128 * (age - 40) - 0.0194 * (age - 18)
    elif age > 40:
        xb += 0.0128 * (age - 40)
        
    xb += -0.0464 * ((height_cm / 100) - 1.70)
    if weight_kg < 80:
        xb += -0.0199 * ((weight_kg / 100) - 0.80)
        
    if eth_black: xb += 0.179
    if htn: xb += 0.126
    if diab: xb += 0.130
    if cod_cva: xb += 0.0881
    
    creat_val = min(creat, 8.0) 
    xb += 0.220 * (creat_val - 1.0)
    if creat_val > 1.5:
        xb += -0.209 * (creat_val - 1.5)
        
    if hcv: xb += 0.240
    if dcd: xb += 0.133
    
    kdri_raw = math.exp(xb)
    scaling_factor = 1.250 
    kdri_scaled = kdri_raw / scaling_factor
    
    return kdri_raw, kdri_scaled

def estimate_kdpi(kdri_scaled):
    """Approximates KDPI percentile mapping from Scaled KDRI."""
    if kdri_scaled <= 0.70: return int(kdri_scaled * 30)
    elif kdri_scaled <= 1.0: return int(21 + (kdri_scaled - 0.70) * 100)
    elif kdri_scaled <= 1.5: return int(51 + (kdri_scaled - 1.0) * 60)
    else: return min(100, int(81 + (kdri_scaled - 1.5) * 30))

# --- Title Header ---
st.title("🩺 Kidney Utilization Prediction System")
st.markdown("**Second-Opinion AI for Marginal Organ Assessment** | *Data-driven confidence for high-stakes transplant decisions.*")
st.divider()

# --- Tab Layout ---
tab_calc, tab_guide, tab_method, tab_author = st.tabs([
    "📊 Risk Calculator", 
    "📖 User Guide", 
    "🧠 Methodology & Statistics", 
    "👨‍⚕️ Author Details"
])

# ==========================================
# TAB 1: THE 3:00 AM CALCULATOR
# ==========================================
with tab_calc:
    col_input, col_output = st.columns([1.1, 1], gap="large")

    with col_input:
        st.subheader("Donor Clinical Profile")
        st.info("Input donor parameters to generate a calibrated utilization probability.")
        
        with st.container(border=True):
            st.markdown("**Biometrics & Demographics**")
            col1, col2, col3 = st.columns(3)
            with col1:
                donor_age = st.number_input("Age (Yrs)", min_value=0, max_value=100, value=55)
            with col2:
                donor_hgt = st.number_input("Height (cm)", min_value=50, max_value=250, value=175)
            with col3:
                donor_wgt = st.number_input("Weight (kg)", min_value=10, max_value=250, value=85)
            
            donor_bmi = donor_wgt / ((donor_hgt / 100) ** 2) if donor_hgt > 0 else 0
            eth_black = st.checkbox("Donor of African Descent (Used in KDRI calc)", value=False)
        
        with st.container(border=True):
            st.markdown("**Clinical History & Procurement**")
            col4, col5 = st.columns(2)
            with col4:
                # We use strings here to ensure compatibility
                history_htn = st.selectbox("Hypertension", options=[("No/Unknown", "1"), ("Yes", "5")], format_func=lambda x: x[0])[1]
                cod_dict = {"Anoxia": "1", "CVA/Stroke": "2", "Head Trauma": "3", "CNS Tumor": "4", "Other": "999"}
                cause_of_death = st.selectbox("Cause of Death", options=list(cod_dict.keys()))
                is_dcd = st.selectbox("DCD (Circulatory Death)", options=[("No (Brain Death)", "0"), ("Yes (DCD)", "1")], format_func=lambda x: x[0])[1]
            with col5:
                history_diab = st.selectbox("Diabetes", options=[("No/Unknown", "1"), ("Yes", "5")], format_func=lambda x: x[0])[1]
                hcv_status = st.selectbox("HCV Antibody", options=[("Negative", "N"), ("Positive", "P")], format_func=lambda x: x[0])[1]
                terminal_creat = st.number_input("Terminal Creatinine (mg/dL)", min_value=0.1, max_value=15.0, value=2.1, step=0.1)

        with st.container(border=True):
            st.markdown("**Organ Quality Index (KDPI)**")
            kdpi_mode = st.radio("KDPI Entry Method", ["Auto-Calculate (OPTN Formula)", "Manual Entry (From DonorNet)"], horizontal=True)
            
            if kdpi_mode == "Auto-Calculate (OPTN Formula)":
                kdri_raw, kdri_scaled = calculate_kdri(
                    donor_age, donor_hgt, donor_wgt, eth_black, int(history_htn)==5, 
                    int(history_diab)==5, (cause_of_death == "CVA/Stroke"), terminal_creat, (hcv_status == "P"), int(is_dcd)==1
                )
                kdpi = estimate_kdpi(kdri_scaled)
                
                cA, cB, cC = st.columns(3)
                cA.metric("Calculated BMI", f"{donor_bmi:.1f}")
                cB.metric("Scaled KDRI", f"{kdri_scaled:.2f}")
                cC.metric("Estimated KDPI", f"{kdpi}%")
            else:
                kdpi = st.number_input("Enter Official KDPI (%)", min_value=0, max_value=100, value=85)

    with col_output:
        st.subheader("Prediction Dashboard")
        
        # 1. Prepare raw data dictionary
        # Note: We keep categorical raw values as strings here to ensure we handle the mapping carefully
        data = {
            'donor_age': float(donor_age), 
            'donor_bmi': float(donor_bmi), 
            'terminal_creatinine': float(terminal_creat),
            'history_htn': str(history_htn),           # String for now
            'history_diabetes': str(history_diab),     # String for now
            'cause_of_death': str(cod_dict[cause_of_death]), # String for now
            'kdpi': float(kdpi),
            'is_dcd': float(is_dcd),                   # float
            'hcv_status': float(1.0 if hcv_status == "P" else 0.0) # Map to float exactly like pipeline
        }
        
        # 2. Build DataFrame
        input_df = pd.DataFrame([data])
        
        # 3. Align columns to match the trained model's feature list exactly
        input_df = input_df[deployed_model['features']]
        
        # 4. STRICT TYPE CASTING (Must match training data exactly)
        
        # Categorical columns (these were 'object' in the CSV and not in binary_map)
        cat_cols = ['history_htn', 'history_diabetes', 'cause_of_death']
        for col in cat_cols:
            if col in input_df.columns:
                # Force to category type
                input_df[col] = input_df[col].astype('category')
        
        # Numeric columns (everything else)
        for col in input_df.columns:
            if col not in cat_cols:
                input_df[col] = input_df[col].astype(float)

        # 5. REAL INFERENCE EXECUTION
        prob_success, top_factors = predict_with_explanations(
            deployed_model['calibrator'], 
            deployed_model['base_model'], 
            input_df
        )

        # Confidence Gauge Visualization
        fig = go.Figure(go.Indicator(
            mode = "gauge+number",
            value = prob_success * 100,
            domain = {'x': [0, 1], 'y': [0, 1]},
            number = {'suffix': "%", 'font': {'size': 54, 'color': '#111827', 'weight': 'bold'}},
            title = {'text': "Calibrated Transplant Probability", 'font': {'size': 18, 'color': '#6B7280'}},
            gauge = {
                'axis': {'range': [None, 100], 'tickwidth': 1, 'tickcolor': "darkblue"},
                'bar': {'color': "rgba(0,0,0,0)"},
                'bgcolor': "white",
                'borderwidth': 2,
                'bordercolor': "#E5E7EB",
                'steps': [
                    {'range': [0, 40], 'color': "#EF4444"},    # Red (High Risk Discard)
                    {'range': [40, 70], 'color': "#FBBF24"},   # Yellow (Marginal/Borderline)
                    {'range': [70, 100], 'color': "#10B981"}   # Green (High Success)
                ],
                'threshold': {
                    'line': {'color': "#111827", 'width': 5},
                    'thickness': 0.75,
                    'value': prob_success * 100
                }
            }
        ))
        fig.update_layout(height=400, margin=dict(l=20, r=20, t=50, b=20))
        st.plotly_chart(fig, use_container_width=True)

        st.markdown("#### 🔍 Interpretable Drivers (SHAP)")
        st.caption("The mathematical impact of this specific donor's physiology on the final score:")
        
        for i, factor in enumerate(top_factors):
            if "Decreased" in factor:
                st.error(f"**{i+1}.** {factor}", icon="📉")
            else:
                st.success(f"**{i+1}.** {factor}", icon="📈")

# ==========================================
# TAB 2: USER GUIDE
# ==========================================
with tab_guide:
    st.header("📖 Clinical User Guide")
    st.markdown("""
    This tool provides a rapid, statistically robust assessment of marginal donor kidneys. It is designed to act as a **"second opinion"** to assist transplant teams in organ acceptance decisions.
    """)
    
    with st.expander("Step 1: Input Clinical Data (DonorNet Profile)", expanded=True):
        st.markdown("""
        Review the OPTN/DonorNet offer and enter the variables into the **Risk Calculator** tab.
        * **Biometrics:** Age, Height, and Weight auto-calculate BMI and feed into the KDRI score.
        * **Procurement Factors:** Accurate DCD (Circulatory Death) and HCV status are vital, as they dramatically alter the baseline risk curve in the algorithm.
        * **KDPI Automation:** You may manually enter the official OPTN KDPI, or allow the app to calculate the Donor Risk Index (KDRI) via the standard Rao et al. formula.
        """)
        
    with st.expander("Step 2: Interpret the Calibrated Confidence Score"):
        st.markdown("""
        The dial represents the **Calibrated Utilization Probability**. 
        Because the model undergoes *Isotonic Regression calibration*, this percentage is a true historical mirror: if the gauge says 65%, it means 65% of historically identical organs were successfully transplanted.
        
        * 🟢 **Green Zone (70% - 100%):** Standard utility. Minimal overlapping risk factors.
        * 🟡 **Yellow Zone (40% - 70%):** Marginal utility. Organ possesses compounding clinical deficits. Evaluate the SHAP drivers carefully against your recipient's waitlist mortality risk.
        * 🔴 **Red Zone (0% - 40%):** High discard likelihood. Historically, organs matching this physiological profile are overwhelmingly discarded by transplant centers.
        """)

    with st.expander("Step 3: Analyze SHAP Explainability"):
        st.markdown("""
        No AI should operate as a black box in medicine. The **Interpretable Drivers** section utilizes SHAP (SHapley Additive exPlanations) to crack open the algorithm.
        
        It calculates the exact marginal contribution of each variable. For instance, if an organ has an excellent KDPI but a poor terminal creatinine, the SHAP output will quantify exactly which factor overpowered the other to generate the final percentage.
        """)

# ==========================================
# TAB 3: METHODOLOGY
# ==========================================
with tab_method:
    st.header("Pipeline Architecture & Statistical Rigor")
    st.markdown("""
    Predictive modeling in transplant medicine requires extreme safeguards against **Data Leakage** and **Overfitting**. 
    This model was developed using the massive historical OPTN STAR database, utilizing a resilient, clinical-first pipeline.
    """)
    
    col_m1, col_m2 = st.columns(2)
    
    with col_m1:
        st.subheader("1. Aggressive Leakage Purge")
        st.markdown("""
        Feeding post-transplant data to an algorithm results in models that "cheat" by seeing the future.
        * **Regex Sanitization:** Before training, the 1,000+ STAR columns underwent an aggressive regex purge. All recipient follow-up data, post-clamp biopsy results, survival dates, and discard reason codes were systematically obliterated.
        * **Missingness Ceiling:** Clinical variables with >85% missingness were dropped to prevent imputation bias.
        """)
        
        st.subheader("2. Resilient ML Architecture")
        st.markdown("""
        * **LightGBM Classifier:** Chosen for its native mathematical handling of `NaN` values and categorical data, eliminating the need for rigid/flawed data imputation.
        * **Early Stopping & Subsampling:** The model utilizes Stratified splits (Train/Val/Test). To prevent overfitting on clinical outliers, the tree depth is strictly constrained (`max_depth=7`), and training relies on *Early Stopping*—halting the algorithm the moment it stops improving on unseen validation data.
        """)
        
    with col_m2:
        st.subheader("3. Calibration & Imbalance Handling")
        st.markdown("""
        * **Precision-Recall AUC (PR-AUC):** Because organ utilization datasets are highly imbalanced, standard ROC-AUC is misleading. This model's primary evaluation metric is PR-AUC, forcing it to maintain precision on the minority class (marginal/discarded organs).
        * **Pre-Fit Isotonic Calibration:** Raw probabilities from tree-based models are clinically unsafe. The outputs are passed through an Isotonic Regression calibrator on an unseen dataset to guarantee the percentages represent true real-world frequencies.
        """)
        
        st.subheader("4. Feature Distillation")
        st.markdown("""
        While trained on the full sanitized STAR array, deployment requires speed. Using SHAP value mapping and Information Gain splits, the full array was distilled into the **top 9 highest-yield pre-recovery predictors**. This preserves >90% of the statistical variance while preventing data-entry fatigue for surgeons.
        """)

# ==========================================
# TAB 4: AUTHOR DETAILS
# ==========================================
with tab_author:
    st.header("👨‍⚕️ About the Creator")
    
    col_a1, col_a2 = st.columns([1, 4])
    
    with col_a1:
        st.image("https://api.dicebear.com/7.x/initials/svg?seed=NA&backgroundColor=0369a1", width=180)
        
    with col_a2:
        st.subheader("Neel Agarwal")
        st.markdown("**Medical Student | Clinical Researcher**")
        st.markdown("*The Ohio State University College of Medicine | Founder, G.E.M.I.N.I.*")
        
        st.markdown("""
        **Project Mission:** Bridging the gap between biostatistics and the operating room. This application aims to empower transplant surgeons with data-driven, mathematically sound tools to safely expand the donor pool and improve patient access to life-saving transplants.
        
        *Specializing in Transplant Medicine (Nephrology/Urology), Predictive Analytics, and Health-Tech integrations.*
        """)
        
        st.markdown(f"📧 **Contact:** [neel.agarwal@osumc.edu](mailto:neel.agarwal@osumc.edu)")